[package]
name = "circuits-stark-verifier-examples"
version.workspace = true
edition.workspace = true

[dependencies]
circuits.workspace = true
circuits-stark-verifier.workspace = true
itertools.workspace = true
num-traits.workspace = true
stwo.workspace = true
stwo-constraint-framework.workspace = true

[dev-dependencies]
rstest.workspace = true
expect-test.workspace = true
